## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [30]:
import numpy as np
import pandas as pd
import scipy as stats

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [18]:
samples =  np.random.normal(15,100,1000)
samples

array([-3.73811521e+01,  9.23871298e+01, -3.01393302e+01, -3.15382941e+01,
       -8.90348926e+01,  1.35210587e+02,  2.71611388e+01,  1.00628418e+02,
        1.63565922e+02, -1.07159468e+01, -1.62290661e+02,  8.63199772e+01,
        1.60475020e+02,  1.02187230e+02, -6.63334109e-01,  1.43501309e+02,
       -4.61102314e+01, -1.50924944e+02, -1.51896850e+01, -1.93154175e+02,
       -1.63878125e+01, -8.38440441e+01, -8.96655583e+01, -1.54564044e+02,
       -4.54373061e+01,  2.94767020e+01, -8.07859703e+01, -9.57327858e+01,
       -5.85985682e+01, -1.56150817e+02, -6.60277260e+01,  1.44572173e+02,
        1.64233783e+02, -1.00549104e+02, -1.00274270e+02, -5.71778928e+01,
       -1.61505808e+02,  2.97877120e+01, -5.29069728e+01, -1.08684243e+02,
       -1.58559101e+02, -4.62047928e+01,  7.44919151e+00,  1.45975912e+02,
        3.90229280e+01,  2.25232732e+01,  3.94446541e+01,  1.03428840e+02,
       -8.10723714e+01,  1.26962193e+02, -1.64892425e+02,  1.86192788e+00,
       -3.94141029e+01,  

Compute the **mean**, **median**, and **mode**

In [19]:
mean = np.mean(samples)
median = np.median(samples)
mean

13.426001749903348

In [20]:
median

20.16672805036515

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [24]:
min = np.min(samples)
max = np.max(samples)
q1 = np.quantile(samples, 0.25)
q3 = np.quantile(samples, 0.75)
iqr = q3-q1

In [25]:
min

-254.97979312059755

In [26]:
max

323.7651549299904

In [27]:
q1

-57.28322589363661

In [28]:
q3

83.7755383792524

In [29]:
iqr

141.058764272889

Compute the **variance** and **standard deviation**

In [21]:
variance = np.var(samples)
std_dev = np.std(samples)
variance

9350.593687150611

In [22]:
std_dev

96.69846786351174

Compute the **skewness** and **kurtosis**

In [39]:
skewness = stats.skewness(samples)
kurtosis = stats.kurtosis(samples)

AttributeError: ignored

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [35]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [42]:
y = (1,2,3,4,5,6,7,8,9,10)
narray = np.array(y)
narray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [44]:
r = np.correlate(x,y)
r

array([880])

## Pandas Correlation Calculation

Run the code below

In [4]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [ ]:
r = 

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [ ]:
rho =

## Seaborn Dataset Tips

Import Seaborn Library

In [1]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [3]:
tips = sns.load_dataset("tips")
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [4]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns